### ISSUE TITLE
Ajax Track Course to be revised 

### ISSUE THREAD

**Issue by MichaelsCode** [MichaelsCode/treehouse#2]
## TODO
- [ ]Take the whole course again
- [ ]Perform changes in sublime
- [ ]Push changes to GitHub repo

🎉 🙆‍♂️ 🎊
